### ISSUE TITLE
Add usage example to Readme

### ISSUE THREAD

**Issue by csd-oss** [runspacegit/daemon#8]
I would like to try it, but it seems unclear how to use it. I suggest adding instructions about how to use it. We can try to run it on two of my local machines and after we do it successfully I can update readme with instructions.

**Comment by 0x77dev** [comment]
https://github.com/runspacegit/daemon/README.md / https://github.com/runspacegit/daemon/commit/e6bed9396ed4cc96d529acbf4d0687ba15e765a3
